# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """
$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$username\
$sudo\
$directory\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$fill\
$singularity\
$kubernetes\
$vcsh\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$os\
$container\
$battery\
$time
$character
"""
# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '
add_newline = false

[kotlin]
symbol = " "

[elixir]
symbol = " "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[golang]
symbol = " "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = " "
format = " hs [$symbol($version )]($style)"

[env_var.VIMSHELL] # vim subshell
format = "[$env_value]($style)"
style = 'green italic'

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[[battery.display]]
threshold = 40
style = "dimmed yellow"

[[battery.display]]
threshold = 70
style = "dimmed white"

[directory]
read_only = " 󰌾"
# fish_style_pwd_dir_length = 0
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false
style = "italic blue"
format = ' [$path]($style)[$read_only]($read_only_style)'

[perl]
symbol = " "

[pijul_channel]
symbol = " "

[ocaml]
symbol = " "

[swift]
symbol = " "
format = " sw [${symbol}${version}]($style)"
style = "italic bright-red"
version_format = "${major}.${minor}"

[deno]
format = " deno [∫ $version](blue italic)"
version_format = "${major}.${minor}"

[c]
symbol = " "
format = " c [$symbol($version(-$name))]($style)"

[dart]
symbol = " "
format = " dart [$symbol($version )]($style)"

[git_branch]
symbol = " "
format = "[ $symbol $branch(:$remote_branch)]($style)"
style = "bold italic white"

[julia]
symbol = " "
format = " jl [$symbol($version )]($style)"

[package]
symbol = "󰏗 "
format = " pkg [$symbol$version]($style)"
version_format = "${major}.${minor}"
style = "bright-yellow italic"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[elm]
symbol = "◩ "
format = " elm [$symbol($version )]($style)"

[guix_shell]
symbol = " "

[buf]
symbol = " "
format = " buf [$symbol $version $buf_version]($style)"

[nim]
symbol = "󰆥 "
format = " nim [$symbol($version )]($style)"

[cmd_duration]
min_time = 500
format = "[$duration ](italic bright-yellow)"

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"

[rust]
symbol = " "
format = " rs [$symbol$version]($style)"
version_format = "${major}.${minor}"
style = "italic red"

[conda]
symbol = " "
format = " conda [$symbol$environment]($style)"

[memory_usage]
symbol = "󰍛 "
format = " mem [${ram}( ${swap})]($style)"

[nix_shell]
symbol = " "
format = " nix [$symbol$state $name]($style)"

[nodejs]
symbol = " "
format = " node [◫ ($version)](italic bright-green)"
detect_files = ["package-lock.json", "yarn.lock"]
version_format = "${major}.${minor}"

[ruby]
symbol = " "
format = " rb [${symbol}${version}]($style)"
version_format = "${major}.${minor}"
style = "italic red"

[sudo]
format = "[$symbol]($style)"
style = "italic bright-purple"
symbol = "◇┈"
disabled = false

[rlang]
symbol = "󰟔 "

[character]
format = "$symbol "
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[jobs]
format = "[ $symbol$number]($style)"
style = "white"
symbol = "[▶ ](blue italic)"

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[meson]
symbol = "󰔷 "

[username]
style_user = "yellow bold"
style_root = "purple bold italic"
format = "[$user]($style) ▻ "
disabled = false

[lua]
symbol = " "
format = " lua [${symbol}${version}]($style)"
style = "italic bright-yellow"

[python]
symbol = " "
format = " py [${symbol}${version}]($style)"
version_format = "${major}.${minor}"
style = "italic bright-yellow"

[scala]
symbol = " "

[line_break]
disabled = true

[git_status]
style = "italic bright-blue"
format = """([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"""
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▲│[${count}](bold white)│](italic green)"
behind = "[▽│[${count}](bold white)│](italic red)"
diverged = "[◇ ▲┤[${ahead_count}](regular white)│▽┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◦◫◦](italic white)"
modified = "[●◦](italic yellow)"
staged = "[■┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"

[crystal]
symbol = " "

[fennel]
symbol = " "

[haxe]
symbol = " "

[aws]
symbol = "  "
format = " aws [$symbol $profile $region]($style)"
style = "italic blue"

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "[█](italic green)"
charging_symbol = "[↑](italic green)"
discharging_symbol = "[↓](italic)"
unknown_symbol = "[░](italic)"
empty_symbol = "[▃](italic red)"

[php]
symbol = " "

[zig]
symbol = " "

[fill]
symbol = "-"
